export const rws = [
    {
        name: "Wartość Energetyczna",
        group: "Wartość Energetyczna",
        value: 2000,
        variant: "greenToRed",
    },
    {
        name: "Total",
        group: "Tłuszcz",
        displayName: "Tłuszcz",
        value: 70,
        variant: "greenToRed",
    },
    {
        name: "Kwasy nasycone",
        group: "Tłuszcz",
        displayName: "w tym kwasy tłuszczowe nasycone",
        value: 20,
        variant: "greenToRed",
    },
    {
        name: "Total",
        group: "Węglowodany",
        displayName: "Węglowodany",
        value: 260,
        variant: "greenToLightGreen",
    },
    {
        name: "Cukry",
        group: "Węglowodany",
        displayName: "w tym cukry",
        value: 90,
        variant: "greenToRed",
    },
    { name: "Białko", group: "Białko", value: 50, variant: "greenToLightGreen" },
    { name: "Sól", group: "Sól", value: 6, variant: "greenToRed" },
    { name: "Błonnik", group: "Błonnik", variant: "blueToGreen" },
];

export const rwsV = [
    {
        name: "Witamina A",
        group: "Witaminy",
        value: 800,
        variant: "blueToGreen",
        unit: "µg",
    },
    {
        name: "Witamina D",
        group: "Witaminy",
        value: 5,
        variant: "blueToGreen",
        unit: "µg",
    },
    {
        name: "Witamina E",
        group: "Witaminy",
        value: 12,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Witamina K",
        group: "Witaminy",
        value: 75,
        variant: "blueToGreen",
        unit: "µg",
    },
    {
        name: "Witamina C",
        group: "Witaminy",
        value: 80,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Witamina B6",
        group: "Witaminy",
        value: 1.4,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Witamina B12",
        group: "Witaminy",
        value: 2.5,
        variant: "blueToGreen",
        unit: "µg",
    },
];

export const rwsM = [
    {
        name: "Magnez",
        group: "Minerały",
        value: 375,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Fluorek",
        group: "Minerały",
        value: 3.5,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Mangan",
        group: "Minerały",
        value: 2,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Wapń",
        group: "Minerały",
        value: 800,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Miedź",
        group: "Minerały",
        value: 1,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Żelazo",
        group: "Minerały",
        value: 14,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Selen",
        group: "Minerały",
        value: 55,
        variant: "blueToGreen",
        unit: "µg",
    },
    {
        name: "Molibden",
        group: "Minerały",
        value: 50,
        variant: "blueToGreen",
        unit: "µg",
    },
    {
        name: "Fosfor",
        group: "Minerały",
        value: 700,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Jod",
        group: "Minerały",
        value: 150,
        variant: "blueToGreen",
        unit: "µg",
    },
    {
        name: "Chrom",
        group: "Minerały",
        value: 40,
        variant: "blueToGreen",
        unit: "µg",
    },
    {
        name: "Potas",
        group: "Minerały",
        value: 2000,
        variant: "blueToGreen",
        unit: "mg",
    },
    {
        name: "Cynk",
        group: "Minerały",
        value: 10,
        variant: "blueToGreen",
        unit: "mg",
    },
];
