export const rws = [
    {
        name: "Wartość Energetyczna",
        group: "Wartość Energetyczna",
        value: 2000,
        variant: "greenToYellow",
        key: "energyValue",
    },
    {
        name: "Total",
        group: "Tłuszcz",
        displayName: "Tłuszcz",
        value: 70,
        variant: "greenToYellow",
        key: "totalFat",
    },
    {
        name: "Kwasy nasycone",
        group: "Tłuszcz",
        displayName: "w tym kwasy tłuszczowe nasycone",
        value: 20,
        variant: "greenToRed",
        key: "saturatedFat",
    },
    {
        name: "Total",
        group: "Węglowodany",
        displayName: "Węglowodany",
        value: 260,
        variant: "greenToYellow",
        key: "totalCarbohydrates",
    },
    {
        name: "Cukry",
        group: "Węglowodany",
        displayName: "w tym cukry",
        value: 90,
        variant: "greenToRed",
        key: "sugars",
    },
    { name: "Białko", group: "Białko", value: 50, variant: "greenToLightGreen", key: "protein" },
    { name: "Sól", group: "Sól", value: 6, variant: "greenToRed", key: "salt" },
    { name: "Błonnik", group: "Błonnik", key: "fiber" },
];

export const rwsV = [
    {
        name: "Witamina A",
        group: "Witaminy",
        value: 800,
        variant: "blueToGreen",
        unit: "µg",
        key: "vitaminA",
    },
    {
        name: "Witamina D",
        group: "Witaminy",
        value: 5,
        variant: "blueToGreen",
        unit: "µg",
        key: "vitaminD",
    },
    {
        name: "Witamina E",
        group: "Witaminy",
        value: 12,
        variant: "blueToGreen",
        unit: "mg",
        key: "vitaminE",
    },
    {
        name: "Witamina K",
        group: "Witaminy",
        value: 75,
        variant: "blueToGreen",
        unit: "µg",
        key: "vitaminK",
    },
    {
        name: "Witamina C",
        group: "Witaminy",
        value: 80,
        variant: "blueToGreen",
        unit: "mg",
        key: "vitaminC",
    },
    {
        name: "Witamina B6",
        group: "Witaminy",
        value: 1.4,
        variant: "blueToGreen",
        unit: "mg",
        key: "vitaminB6",
    },
    {
        name: "Witamina B12",
        group: "Witaminy",
        value: 2.5,
        variant: "blueToGreen",
        unit: "µg",
        key: "vitaminB12",
    },
];

export const rwsM = [
    {
        name: "Magnez",
        group: "Minerały",
        value: 375,
        variant: "blueToGreen",
        unit: "mg",
        key: "magnesium",
    },
    {
        name: "Fluorek",
        group: "Minerały",
        value: 3.5,
        variant: "blueToGreen",
        unit: "mg",
        key: "fluoride",
    },
    {
        name: "Mangan",
        group: "Minerały",
        value: 2,
        variant: "blueToGreen",
        unit: "mg",
        key: "manganese",
    },
    {
        name: "Wapń",
        group: "Minerały",
        value: 800,
        variant: "blueToGreen",
        unit: "mg",
        key: "calcium",
    },
    {
        name: "Miedź",
        group: "Minerały",
        value: 1,
        variant: "blueToGreen",
        unit: "mg",
        key: "copper",
    },
    {
        name: "Żelazo",
        group: "Minerały",
        value: 14,
        variant: "blueToGreen",
        unit: "mg",
        key: "iron",
    },
    {
        name: "Selen",
        group: "Minerały",
        value: 55,
        variant: "blueToGreen",
        unit: "µg",
        key: "selenium",
    },
    {
        name: "Molibden",
        group: "Minerały",
        value: 50,
        variant: "blueToGreen",
        unit: "µg",
        key: "molybdenum",
    },
    {
        name: "Fosfor",
        group: "Minerały",
        value: 700,
        variant: "blueToGreen",
        unit: "mg",
        key: "phosphorus",
    },
    {
        name: "Jod",
        group: "Minerały",
        value: 150,
        variant: "blueToGreen",
        unit: "µg",
        key: "iodine",
    },
    {
        name: "Chrom",
        group: "Minerały",
        value: 40,
        variant: "blueToGreen",
        unit: "µg",
        key: "chromium",
    },
    {
        name: "Potas",
        group: "Minerały",
        value: 2000,
        variant: "blueToGreen",
        unit: "mg",
        key: "potassium",
    },
    {
        name: "Cynk",
        group: "Minerały",
        value: 10,
        variant: "blueToGreen",
        unit: "mg",
        key: "zinc",
    },
];
