server:
  servlet:
    context-path: /api

spring:
  flyway:
    url: jdbc:postgresql://nutrixplorer-db:5432/nutrixplorer
  mail:
    host: nutrixplorer-mail
logging:
  file:
    name: /var/log/nutrixplorer.log
datasource:
  admin:
    jdbc-url: "jdbc:postgresql://nutrixplorer-db:5432/nutrixplorer"
    username: ${ADMIN_DB_USER}
    password: ${ADMIN_DB_PASSWORD}
  user:
    jdbc-url: "jdbc:postgresql://nutrixplorer-db:5432/nutrixplorer"
    username: ${USER_DB_USER}
    password: ${USER_DB_PASSWORD}

nutrixplorer:
  proxy: true
  frontend-url: https://localhost
  jws:
    secret: ${JWS_SECRET_KEY}
  oauth:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_url: https://localhost/auth/google/callback
    token_url: https://oauth2.googleapis.com/token