spring:
  application:
    name: nutrixplorer
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrixplorer
    username: nutriadmin
    password: adminP@ssw0rd
    driverClassname: org.postgresql.Driver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    web: debug
    org:
      springframework:
        security: debug