spring:
  application:
    name: nutrixplorer
  flyway:
    locations: classpath:db
    user: nutriadmin
    password: adminP@ssw0rd
    url: jdbc:postgresql://localhost:5432/nutrixplorer
    driver-class-name: org.postgresql.Driver
    enabled: true
    default-schema: public
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: localhost
    port: 25
    properties:
      auth: false
      starttls:
        enable: false
datasource:
  admin:
    jdbc-url: "jdbc:postgresql://localhost:5432/nutrixplorer"
    username: nutriadmin
    password: adminP@ssw0rd
  mokuser:
    jdbc-url: "jdbc:postgresql://localhost:5432/nutrixplorer"
    username: nutrimokuser
    password: mokP@ssw0rd
  mowuser:
    jdbc-url: "jdbc:postgresql://localhost:5432/nutrixplorer"
    username: nutrimowuser
    password: mowP@ssw0rd
#logging:
#  level:
#    web: debug
#    org:
#    hibernate:
#      type:
#        descriptor:
#          sql:
#            BasicBinder: trace
#      springframework:
#        transaction: debug
#        transaction.interceptor: trace
#        security: debug
#        orm:
#          jpa: debug

    sql: debug
nutrixplorer:
  transaction:
    timeout: 15
  remove-unverified: 24
  frontend-url: http://localhost:3000
  login:
    max-attempts: 3
    lock-duration: 300
  jwt:
    public-key-path: classpath:public.pem
    private-key-path: classpath:private.pem
    expiration: 12
  jws:
    secret: ZhLR58MdJjGl6MAlEC9OWUkS34KTEsYd
  oauth:
    client_id: 848010620252-mmpisp9fchf67grpc5g03p0fdkenqrmu.apps.googleusercontent.com
    client_secret: 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
    redirect_url: http://localhost:3000/auth/google/callback
    token_url: https://oauth2.googleapis.com/token