spring:
  application:
    name: overexploration
logging:
  level:
    web: debug
    org:
      springframework:
        transaction: debug
        security: debug
        orm:
          jpa: debug
    sql: debug

nutrixplorer:
  jwt:
    public-key-path: classpath:public.pem
    private-key-path: classpath:private.pem
    expiration: 1