server:
  servlet:
    context-path: /api

spring:
  flyway:
    locations: classpath:db
    driver-class-name: org.postgresql.Driver
    enabled: true
    default-schema: public
    baseline-on-migrate: true
    url: ${DB_URL}
    user: ${ADMIN_DB_USER}
    password: ${ADMIN_DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: /var/log/nutrixplorer.log

datasource:
  admin:
    jdbc-url: ${DB_URL}
    username: ${ADMIN_DB_USER}
    password: ${ADMIN_DB_PASSWORD}
  mokuser:
    jdbc-url: ${DB_URL}
    username: ${MOK_DB_USER}
    password: ${MOK_DB_PASSWORD}
  mowuser:
    jdbc-url: ${DB_URL}
    username: ${MOW_DB_USER}
    password: ${MOW_DB_PASSWORD}

nutrixplorer:
  remove-unverified: 24
  login:
    max-attempts: 3
    lock-duration: 300
  jwt:
    public-key-path: classpath:public.pem
    private-key-path: classpath:private.pem
    expiration: 12
  transaction:
    timeout: 15
  frontend-url: ${FRONTEND_URL}
  jws:
    secret: ${JWS_SECRET_KEY}
  oauth:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_url: ${GOOGLE_REDIRECT_URL}
    token_url: https://oauth2.googleapis.com/token