services:
  db:
    image: postgres:16
    container_name: nutrixplorer-db
    restart: always
    environment:
      POSTGRES_USER: nutriadmin
      POSTGRES_PASSWORD: adminP@ssw0rd
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init1.sql
  mail:
    image: rnwood/smtp4dev:3.6.1
    container_name: nutrixplorer-mail
    restart: always
    ports:
      - "5000:80"
      - "25:25"
    networks:
      - my_network
networks:
  my_network: