services:
  db:
    image: postgres:16.2
    container_name: nutrixplorer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init1.sql
  mail:
    image: rnwood/smtp4dev
    container_name: nutrixplorer-mail
    restart: always
    ports:
      - "5000:80"
      - "25:25"
    networks:
      - my_network
  tomcat:
    build:
      context: ..
      dockerfile: Docker/DockerfileSpringBoot
      pull: false
    container_name: nutrixplorer-tomcat
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
networks:
  my_network: